version: 1
update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    update_schedule: "monthly"

    automerged_updates:
    - match:
        dependency_type: "development"
        update_type: "semver:patch"
