name: GenRMQ CI

# Reusable YAML templates for common steps across jobs
step_checkout: &step_checkout
  name: Checkout code
  uses: actions/checkout@v2

step_set_up: &step_set_up
  name: Set up Elixir
  uses: actions/setup-elixir@v1
  with:
    elixir-version: '1.10.3'
    otp-version: '22.3'

step_dep_cache: &step_dep_cache
  name: Restore dependencies cache
  uses: actions/cache@v2
  with:
    path: deps
    key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    restore-keys: ${{ runner.os }}-mix-

step_plt_cache: &step_plt_cache
  name: Restore PLT cache
  uses: actions/cache@v2
  with:
    path: priv/plts
    key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    restore-keys: ${{ runner.os }}-mix-

step_install_deps: &step_install_deps
  name: Install dependencies
  run: mix deps.get

# GitHub Actions workflow configuration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
      - <<: *step_checkout
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -v -r .
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - <<: *step_checkout
      - <<: *step_set_up
      - <<: *step_dep_cache
      - <<: *step_install_deps
      - <<: *step_plt_cache
      - name: Mix Formatter
        run: mix format --check-formatted
      - name: Check for compiler warnings
        run: mix compile --warnings-as-errors
      - name: Credo strict checks
        run: mix credo --strict
      - name: Dialyzer checks
        run: mix dialyzer

  unit_test:
    name: Run ExUnit tests
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672

    steps:
      - <<: *step_checkout
      - <<: *step_set_up
      - <<: *step_dep_cache
      - <<: *step_install_deps
      - name: ExUnit tests
        run: mix test
